### ISSUE TITLE
sendcmpct

### ISSUE THREAD

**Issue by tdelabro** [zig-bitcoin/btczee#100]

**Comment by guha-rahul** [comment]
Can i take it up?

**Comment by tdelabro** [comment]
@guha-rahul are you working on this?

**Comment by guha-rahul** [comment]
@tdelabro yessir,  i had some problems so trying to figure that out .

**Comment by tdelabro** [comment]
Do you need help? Maybe if you push a first version of your code I can help you figure it

**Comment by guha-rahul** [comment]
i pushed the code, it needs some changes and being this my first issue , i am having some problems overral but trying to figure it out.

**Comment by tdelabro** [comment]
@guha-rahul good job, I did a review.

**Comment by guha-rahul** [comment]
@tdelabro can you close this since its done?

**Comment by tdelabro** [comment]
closed by #134
