### ISSUE TITLE
Enforce payload size limit on sent message

### ISSUE THREAD

**Issue by gdnathan** [zig-bitcoin/btczee#114]
Following up discussion on #112 .

"To actually enforce the limit, we could do something like this maybe:
``src/network/wire/lib.zig``
```
const MAX_PAYLOAD_SIZE: u32 = 32 * 1024 * 1024

const payload_len: u32 = @intCast(payload.len);
if (payload_len > MAX_PAYLOAD_SIZE) {
    return someerror
}
```
"

**Comment by supreme2580** [comment]
@gdnathan can I be assigned to this?

**Comment by supreme2580** [comment]
@gdnathan I was reading through src/network/wire/lib.zig sendMessage function and I saw const MAX_SIZE: usize = 0x02000000; which is const MAX_PAYLOAD_SIZE: u32 = 32 * 1024 * 1024 and in sendMessage I saw     if (total_message_size > MAX_SIZE) {
        return Error.MessageTooLarge;
    } is it not the same as limiting size on the sent message?

**Comment by tdelabro** [comment]
yes it is. It looks like it is missing from receiveMessage tho. You can add it there too

**Comment by supreme2580** [comment]
Okay great, @tdelabro @gdnathan  can I be assigned to this?

**Comment by gdnathan** [comment]
Hey @supreme2580 just fyi, I'm just a contributor on this project haha not a maintainer, so I cannot assign you to any tasks !
