### ISSUE TITLE
p2p(peer): add support for ipv4 peers

### ISSUE THREAD

**Issue by tdelabro** [zig-bitcoin/btczee#119]
Because the Bitcoin message protocol uses ipv6, I cut corners and only allowed peers that use ipv6

In src/network/peer.zig
```
    pub fn init(allocator: std.mem.Allocator, config: *const Config, address: std.net.Address) !*Peer {
        if (address.any.family != std.posix.AF.INET6) {
            return error.WeOnlySupportIPV6ForNow;
        }
```

Rather than doing this we should accept IPv4 Addresses too and have a function to covert all of them to ipv6 when we need to send messages
posix.AF.INET  is the flag for ipv4.

**Comment by Jonatan-Chaverri** [comment]
I will like to take care of this issue
