### ISSUE TITLE
Optimize BTC script's stack implementation

### ISSUE THREAD

**Issue by tdelabro** [zig-bitcoin/btczee#23]
Right now the BTC script engine's stack is implemented as an array of pointers to the actual values.

Eg:
| index | stack value (pointer) | heap value pointed to | actual size in memory in u8 |
| ---- | ---- | ---- | ---- |
| 100 | 0xbabe | bool | 1 |
| 99 | 0xcafe | i64 | 4 |
| 98 | 0x4242 | [2]u8 | 2 |

This implementation scatters the actual values across the heap, therefore slowing script execution by negating the data-proximity property expected from a heap.
The purpose of this issue would be to implement the stack as an actual stack.

| index | actual value | memory content |
| ---- | ---- | ---- | 
| 100 | false | 0x0 |
| 99 | i64.MAX | 0xff | 
| 98 |  | 0xff |
| 97 | | 0xff |
| 96 | | 0xff |
| 95 | | 0xff |
| 94 | | 0xff |
| 93 | | 0xff |
| 92 | | 0xff |
| 91 | [2]u8{0, 1} | 0x0 |
| 91 |  | 0x1 |

Now the issue is that you don't know in advance what the size of the next item should be. I'm not sure it is an issue, as the script is responsible for telling you how to treat the next item(s) in the stack.
If it becomes an issue there are most likely solutions to be imagined.

**Comment by supreme2580** [comment]
Hi @tdelabro can i be assigned to this?

**Comment by tdelabro** [comment]
@supreme2580 
Tbc we have no certitude this is the correct way to implement it.
Btcd did it the way it is actually done in btczee.
But this implementation in Rust https://github.com/rust-bitcoin/rust-bitcoin/blob/d9b5844981ba5c46eeda3ca68093281e125d425e/bitcoin/src/blockdata/script/owned.rs, seems to do it the way I'm describing it.

Please go ahead and try it out.

**Comment by supreme2580** [comment]
Thanks @tdelabro will check the rust implementation out

**Comment by tdelabro** [comment]
Truth being there is no way to feed the node scripts rn...

**Comment by supreme2580** [comment]
@tdelabro not really, myself and my partner were going over creating more opcodes first... but if this is of high priority we can add this to the issues we're looking at

**Comment by supreme2580** [comment]
@tdelabro what'd you think?

**Comment by tdelabro** [comment]
@supreme2580 sorry I missed you message. Do you have a telegram? So I can add you to our groupchat?

**Comment by tdelabro** [comment]
@supreme2580 I think it's better to work on new opcodes than on this issue for now. 
But truly do whatever you like better :)

**Comment by supreme2580** [comment]
Yes I do I'm supreme1960 on telegram

**Comment by supreme2580** [comment]
Yes we should even have a PR up for more opcodes in a few hours
