### ISSUE TITLE
Implement opcodes 0x71-0x7b

### ISSUE THREAD

**Issue by KhairallahA** [zig-bitcoin/btczee#62]

**Comment by tdelabro** [comment]
hey, don't this conflict with #39 ?

If so please close this issue and your PR as it was claimed beforehand

**Comment by tdelabro** [comment]
unless @varun-doshi is ok to leave you this one, as he will be working on #65?

**Comment by tdelabro** [comment]
As a general rule, @KhairallahA, please refrain from claiming more than 2 issues at the same time

**Comment by KhairallahA** [comment]
hey @tdelabro, but in #39 focus on 0x70-0x72 not same 0x71-0x7b?

**Comment by tdelabro** [comment]
they seem to overlap on 0x71 and 0x72

**Comment by KhairallahA** [comment]
> As a general rule, @KhairallahA, please refrain from claiming more than 2 issues at the same time

Well, I didn't know that.

**Comment by KhairallahA** [comment]
> 0x71

I have checked that 0x71 implementation is different from 0x72.
0x71 uses 0x7b method

**Comment by KhairallahA** [comment]
> they seem to overlap on 0x71 and 0x72

I have checked that 0x71 implementation is different from 0x72.
0x71 uses 0x7b method

**Comment by varun-doshi** [comment]
Hey @KhairallahA you can take up these opcodes.
Let me know if you need any help

**Comment by KhairallahA** [comment]
Hi, @varun-doshi!
Thank you for this, I will
