### ISSUE TITLE
Implement OP_HASH160

### ISSUE THREAD

**Issue by supreme2580** [zig-bitcoin/btczee#71]

**Comment by oluwa-peski** [comment]
Can I take this?

**Comment by tdelabro** [comment]
@oluwa-peski are you working on this?

**Comment by supreme2580** [comment]
@tdelabro I would like to work on this if @oluwa-peski is unavailable

**Comment by tdelabro** [comment]
If I have no answer from him tomorrow I will assign it to you

**Comment by supreme2580** [comment]
Okay thank you
