### ISSUE TITLE
headers

### ISSUE THREAD

**Issue by tdelabro** [zig-bitcoin/btczee#81]

**Comment by ptisserand** [comment]
Hi @tdelabro can I work on this one ?

**Comment by ptisserand** [comment]
Hi @tdelabro , I'm not sure to fully undertstand the following (from https://btcinformation.org/en/developer-reference#headers):
*A [headers](https://btcinformation.org/en/glossary/block-header) message can be empty.*

Does it mean we can have the following:
A- A message header with a payload size of 0
B- A message header with a payload size of 1 and headers.count == 0:  payload will be [0x00]

I have assumed A and B but I'm not sure  to be right.

Thanks for you help.

**Comment by tdelabro** [comment]
It's B
