### ISSUE TITLE
reject

### ISSUE THREAD

**Issue by tdelabro** [zig-bitcoin/btczee#92]

**Comment by raizo07** [comment]
@tdelabro I'll like to work on this

**Comment by tdelabro** [comment]
@raizo07 how are things going?

**Comment by raizo07** [comment]
Hello @tdelabro going good, saw I was assigned today.

**Comment by tdelabro** [comment]
And do you plan to work on it soon?

**Comment by raizo07** [comment]
Yes I am on it.

**Comment by bloomingpeach** [comment]
Can I work on this? @tdelabro

**Comment by bloomingpeach** [comment]
![image](https://github.com/user-attachments/assets/849a3756-6d63-4597-873f-7ec43788a851)
I think this message type is deprecated
