### ISSUE TITLE
filterclear

### ISSUE THREAD

**Issue by tdelabro** [zig-bitcoin/btczee#94]

**Comment by Gerson2102** [comment]
Hey can I work on this one?

**Comment by Gerson2102** [comment]
@gdnathan I was watching [this pr](https://github.com/zig-bitcoin/btczee/pull/106) and [this pr](https://github.com/zig-bitcoin/btczee/pull/111). So I should do something similar to that? In `network/protocol/messages`?

**Comment by gdnathan** [comment]
Hey @Gerson2102 , yeah it's pretty similar as you have no payload
